### ISSUE TITLE
n_clusters

### ISSUE THREAD

**Issue by johnduva** [ocontreras309/ML_Notebooks#1]
Hi Oscar,

Thanks for writing this GMM code, it was really helpful. I did notice one mistake since I wanted to use many clusters. The line `kmeans = KMeans().fit(X)` should be: `kmeans = KMeans(n_clusters).fit(X)` otherwise you can't use more than the default value of 8 clusters (try setting n_clusters to something like 9 to see what I'm talking about).

Thanks!
John

**Comment by johnduva** [comment]
Also, I'm not not sure that the following line requires a loop since there is only one vector of `totals`:

`sample_likelihoods = np.log(np.array([cluster['totals'] for cluster in clusters]))`

**Comment by johnduva** [comment]
I also think you have a few problems with this function:
```
def get_likelihood(X, clusters):
    likelihood = []
    sample_likelihoods = np.log(np.array([cluster['totals'] for cluster in clusters]))
    return np.sum(sample_likelihoods), sample_likelihoods
```
1) `likelihood` is never used 
2) each loop here has the same values for `sample_likelihoods`, since `total` is just a vector

**Comment by ocontreras309** [comment]
Hi @johnduva and thank you for your comments! I've been quite busy, so sorry for the late reply.
Thanks for pointing out. I have fixed the code. Btw totals is changed by the expectation_step function during every epoch, so sample_likelihoods has a different value every time.

Regards

**Comment by ShayneWierbowski** [comment]
Hi Oscar,

I had (I think) a similar question to John regarding the calculation of `sample_likelihoods` here.

For me at least the confusion isn't so much that the value of `cluster['totals']` would never change (as you point out it's updated every expectation_step call). But rather, since `cluster['totals']` is identical for each cluster, the list comprehension over `clusters` seems to be redundant.

I may be missing something, but it seems like this just has the effect of arbitrarily scaling the final likelihood by a factor of `len(clusters)`, and is not supported by the actual equations you show.

Of course practically speaking it doesn't matter for the final optimization, but perhaps it adds more confusion to the code? There's similar confusion in the `expectation_step`...

```python
def expectation_step(X, clusters):
    totals = np.zeros((X.shape[0], 1), dtype=np.float64)
    
    for cluster in clusters:
        pi_k = cluster['pi_k']
        mu_k = cluster['mu_k']
        cov_k = cluster['cov_k']
        
        gamma_nk = (pi_k * gaussian(X, mu_k, cov_k)).astype(np.float64)
        
        for i in range(X.shape[0]):
            totals[i] += gamma_nk[i]
        
        cluster['gamma_nk'] = gamma_nk
        cluster['totals'] = totals
        
    
    for cluster in clusters:
        cluster['gamma_nk'] /= cluster['totals']
```

Where the way it's written with `cluster['totals']` assigned the (incomplete) `total` on each iteration could give the impression that each cluster has a unique total when in fact since they all point to a common vector they all update together. Moving the `cluster['totals' = totals` assignment into the second for loop here would avoid any misinterpretation from not understanding the `cluster['totals]` values are linked. Although I still find it somewhat un-intuitive to have this shared value included in each cluster dictionary (seems to just be a convenience to be able to reference the `totals` vector in the `get_likelihood` function without having a separate `totals` parameter passed).

But other than this minor confusion in the code, this is an excellent explanation and demonstration of Gaussian Mixture Models!

**Comment by ocontreras309** [comment]
@ShayneWierbowski good catch! I have actually improved the EM implementation for better readability. Hope this helps, and thank you!
